name: "Sample React CI pipeline"

on:
    push:
        branches:
            - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js in GitHub Actionss
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: "Checkout node version"
        run: node --version
      - name: "Clone the repository"
        uses: actions/checkout@v2 

